[package]
edition = "2021"
name = "ic-test-utils"
version = "0.1.0"

[dependencies]
dirs = "4.0"
garcon = "0.2"
ic-agent = "0.11"
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
thiserror = "1.0"
ic-cdk = "0.3"
ledger-canister = { git = "https://github.com/flyq/ic" }
