[package]
edition = "2021"
name = "ic-test-utils"
version = "0.2.0"

[dependencies]
dirs = "5.0"
garcon = "0.2"
ic-agent = "0.24"
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
thiserror = "1.0"
candid = "0.8"
